from tkinter import *
root=Tk()
root.geometry("900x500")
root.option_add("*Font","arieal 12 bold")
lbname=Label(root,text="Enter Name:")
lbname.place(relx=0.05,rely=0.09)
textName=Entry(root)
textName.place(relx=0.17,rely=0.09)
lbpassword=Label(root,text="Enter Password:")
lbpassword.place(relx=0.05,rely=0.19)
textPassword=Entry(root)
textPassword.place(relx=0.20,rely=0.19)
subbtn=Button(root,text="submit")
subbtn.place(relx=0.17,rely=0.26)
root.mainloop()
